### PR TITLE
missing schema when updating depth

### PR DESCRIPTION
**Pull request by devmark**

### CODE REVIEW

**Comment by overlookmotel** [comment]
Thanks for this PR. Would you have time to write a test for this?

**Comment by devmark** [comment]
added schema test. 

Because https://github.com/sequelize/sequelize/pull/4939 , so will get a failed testing for now.

**Comment by overlookmotel** [comment]
Thanks @devmark. Would you mind squashing it all to a single commit and then I'll have a look?

Also, I think the two lines:

```js
sql = utils.replaceTableNames(sql, {through: hierarchy.through}, sequelize);
sql = utils.replaceTableNames(sql, {item: model}, sequelize);
```

could be combined into:

```js
sql = utils.replaceTableNames(sql, {
    through: hierarchy.through,
    item: model
}, sequelize);
```

**Comment by teagup** [comment]
Hey @overlookmotel, I've also encountered the issues presented in this PR. It looks like there hasn't been any progress made on this for a while now, and since the issue mentioned in sequelize/sequelize#4939 has since been fixed, the tests may pass now. I can open up a new PR if necessary to get this merged in.

**Comment by overlookmotel** [comment]
I just re-ran the tests on Travis with Sequelize v3.22.0. Tests still failing on Postgres. I haven't had time to look and see why.

I'm afraid I'm really tied up at the moment and am unlikely to be able to look at this in more detail for a week or two at the earliest.

**Comment by overlookmotel** [comment]
But if anyone can get to the bottom of the failing test, that would certainly help...

**Comment by devmark** [comment]
will take a look soon

**Comment by overlookmotel** [comment]
Finally got around to fixing this. It's in v0.6.0.

The problem was actually really simple - bug in Sequelize v2 with `.destroy( { truncate: true } )` not working with schemas.

**Pull request closed without merging**
