### PR TITLE
fix issue #11 (add support for id field customization)

### PR DESCRIPTION
**Pull request by devlato**
Hey, I've just added some functionality to override id field name (the field that is referenced by parentId), so here it is

### CODE REVIEW

**Comment by overlookmotel** [comment]
Sorry this took so long. Too much else going on in my day job and haven't had any time for programming past few months.

I've incorporated your PR in v0.2.10. I rebased it first on my local machine so that's probably why it doesn't show as merged here.

Only change I made was to rename the option for setting the primary key to `primaryKey` rather than `primaryKeyAttribute`, so it matches all the rest.

Thanks loads for the PR and, again, sorry it took so long to get it merged.

**Comment by devlato** [comment]
Thank you!

**Comment by overlookmotel** [comment]
NB this feature it seems is not currently working. #67

**Comment by php-workx** [comment]
Yeah, unfortunately it's not working. You can replicate the issue by simply changing the `folder` model definition in the test suite to something like that:

```
id: {
  type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true,
  field: 'folder_id',
}
```

The result will be an error like `SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'IN/ALL/ANY subquery'`

Caused by this query: 
```
UPDATE `tFolder` SET `hierarchy_level` = `hierarchy_level` + -2 WHERE `id` IN ( SELECT `folder_id` FROM `tFolderAncestors` AS ancestors WHERE ancestors.`ancestor_id` = 104)
```

This is a pretty serious issue cause it affects everybody who is not using default column names.

**Comment by overlookmotel** [comment]
Hi @php-workx. Thanks for raising this.

I never use anything but default column names, so I've never run into this.

Actually, I think it's a separate issue from the issue that this PR was trying to solve - it's due to sequelize-hierarchy ignoring the `field` attribute.

Could you please open a separate issue for this? And, if you feel so inclined, you could also submit a PR?! But please at least open the issue so it's properly on my radar.

**Comment by overlookmotel** [comment]
Issue for @php-workx's problem raised above: #70

**Pull request closed without merging**
