### PR TITLE
Fixed searchPath parameter support

### PR DESCRIPTION
**Pull request by almsh**

### CODE REVIEW

**Comment by almsh** [comment]
Hi @overlookmotel.

The problem occurs when you are using same tables names with hierarchy in different postgres schemas (some kind of namespaces for tables). "Main" query respect schema name (`search_path` parameter) and returns proper result, but queries to tables with hierarchy metadata goes to default `public` schema and receive wrong data or fails with error.

**Comment by overlookmotel** [comment]
@almsh Sorry I am so very slow on coming back on this. If you're still interested in getting this merged can you please point me to something in Sequelize docs that mentions this? If you wanted to write a test, that'd also be very useful.

**Comment by almsh** [comment]
Hi @overlookmotel it's in [`findAll` method](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findAll) options

> options.searchPath | string | optional default: DEFAULT | An optional parameter to specify the schema search_path (Postgres only)

**Comment by overlookmotel** [comment]
Please see https://github.com/overlookmotel/sequelize-hierarchy/issues/129#issuecomment-578410595 as to why I'm closing this issue.

**Pull request closed without merging**
