### PR TITLE
Support sequelize 5

### PR DESCRIPTION
**Pull request by rusekr**
Hello!

Added support for sequelize 5 ( http://docs.sequelizejs.com/manual/upgrade-to-v5.html#model ).

Tested internally on sequelize 4.43.0 and 5.2.1.

### CODE REVIEW

**Comment by rusekr** [comment]
There is single ocassional error in tests with mysql related to  transaction locks:

1) [MYSQL] Tests Methods #bulkUpdate "before each" hook for "sets hierarchyLevel for all rows":
     SequelizeDatabaseError: Deadlock found when trying to get lock; try restarting transaction

Aside of this all logic passes.

**Comment by ccckblaze** [comment]
so, somebody reviewing this merge request?

**Comment by aaronovz1** [comment]
I did a quick review and it looks good. @overlookmotel can we get this checked and merged?

**Comment by overlookmotel** [comment]
Hi @rusekr.

Thanks for working on this and providing a PR. I've just released v2.0.0 including Sequelize v5 support.

I decided to do it a little differently from your PR, but your PR was very helpful in understanding what changes had been made in Sequelize v5. Thank you.

**Comment by overlookmotel** [comment]
@rusekr I just came up against the flaky deadlock error you mentioned in https://github.com/overlookmotel/sequelize-hierarchy/pull/161#issuecomment-477929292.

In my case, it was with Sequelize v2. Did you see the same thing with a more recent version of Sequelize.

**Comment by rusekr** [comment]
https://github.com/overlookmotel/sequelize-hierarchy/issues/162#issuecomment-486920519 - here I wrote. But as I can remember - for me deadlocks was with old sequelize only too. May be in new sequelize developers resolved that conflict themself.

**Pull request closed without merging**
