### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by deksden**
Add some notes about Cascade delete for child nodes

### CODE REVIEW

**Comment by overlookmotel** [comment]
Hi @deksden.

Thanks load for this PR. Before I merge it, I just want to check one thing: when you delete an item, is it also successfully deleting all the rows from the hierarchy table for both the deleted item and all their children?

It's been a while since I wrote this module and I couldn't remember how this worked, so I looked through the code and can't see where deleting rows in the hierarchy table happens. There are no `beforeDelete` or `afterDelete` hooks, so I guess it's relying on the database in `CASCADE` mode to delete the hierarchy table rows too. But I also can't find anywhere in code where it sets the `CASCADE` option. And there's no tests for deletion. So god knows how it's working!

Anyway, what I'm saying is, would you mind checking this all works before we officially recommend use of the `CASCADE` option? And... if you have the time and can be bothered, would be amazing if you wanted to add some tests for this.

**Comment by deksden** [comment]
For me latest commit did work with postgreSQL 9.6 / SQLite3

**Comment by deksden** [comment]
Not sure why jobs .29-.36 on Travis was failed. Look likes some devOps fail. 

Please, help to figure out: for me tests on PostgreSQL works ok for node 4/6/8. I did not have whole range of databases for testing on local machine.

**Comment by deksden** [comment]
Now fixed with ```npm dedupe``` for Travis config.

**Comment by deksden** [comment]
IMHO, now all is ready to merge!

**Comment by overlookmotel** [comment]
Thanks loads for this @deksden. I'd like to look through the test in detail and also try to get my head around this `npm dedupe` business before merging. Unfortunately, I'm working like crazy at the moment and won't have time to get to it for a while. But I won't forget you! Feel free to ping me in a couple of weeks if you've seen no movement.

**Comment by deksden** [comment]
Ok, not problem. 

All that stuff with ```npm dedupe``` is an workaround for some bug/incompatibility of npm@5.3 vs sqlite3: sometimes installing with ```npm install``` of sqlite3 failes without any good reason with weird errors (for ex on Travis). Firing ```npm dedupe``` fixes this. 

Now npm is at 5.4, so maybe it fixed (but not mentioned in changelog). I will try to test it with npm5.4 a little bit later!

**Comment by overlookmotel** [comment]
Have added some text to README and added the test. Couldn't merge directly as couldn't figure out how to get rid of the `npm dedup` business which no longer appears necessary.

**Pull request closed without merging**
